import Solution.Basic.Lecture1
import Solution.Basic.Lecture2
import Solution.Basic.Lecture3
import Solution.Basic.Lecture4
import Solution.Basic.Tactics
import Solution.Advanced.Algebra.Lecture1
import Solution.Advanced.Algebra.Lecture2
import Solution.Advanced.Algebra.Lecture3
import Solution.Advanced.Algebra.Lecture4
import Solution.Advanced.Algebra.Lecture5
import Solution.Advanced.Analysis.Lecture1
import Solution.Advanced.Analysis.Lecture2
import Solution.Advanced.Analysis.Lecture3
import Solution.Advanced.Category.Lecture1
import Solution.Advanced.Category.Lecture2
